name: Build broadcom_cfe_tool on Windows

on:
  push:
    branches:
      - main  # Change to your target branch if needed
  pull_request:
    branches:
      - main  # Change to your target branch if needed

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
        env:
          MSYSTEM: MINGW64

      - name: Compile broadcom_cfe_tool
        # Directly compile all C files in the repository
        run: gcc -o broadcom_cfe_tool.exe *.c
        shell: msys2 {0}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: broadcom_cfe_tool_binary
          path: ./broadcom_cfe_tool.exe
